### Create Manga ###
POST http://localhost:8080/mangas
Content-Type: application/json

{
    "name": "Nome do Manga",
    "description": "Descrição do Manga 2",
    "status": "Status do Manga 2",
    "author": "Autor do Manga 2",
    "publisher": "Editora do Manga 2",
    "dateReleased": "2023-07-20T14:45:39.693689",
    "dateAdded": "2023-07-20T14:45:39.693689",
    "volumes": null,
    "covers": null
}

### List Mangas ###
GET http://localhost:8080/mangas

### Put Manga ###
PUT http://localhost:8080/mangas
Content-Type: application/json

{
    "id": 3,
    "name": "Novo nome do Manga",
    "description": "Nova descrição do Manga",
    "status": "Novo status do Manga",
    "author": "Novo autor do Manga",
    "publisher": "Nova editora do Manga",
    "dateReleased": "2023-07-20T14:45:39.693689",
    "dateAdded": "2023-07-20T14:45:39.693689",
    "volumes": null,
    "covers": null
}

### ADD Volume ###
POST http://localhost:8080/mangas/1/add
Content-Type: application/json

{
    "issue": 1,
    "title": "Volume Two",
    "cover": "Volume Two Cover"
}

### Delete Manga ###
DELETE http://localhost:8080/mangas/3




